
DESE3R:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100  
  
  # Position Controllers ---------------------------------------
  joint_0_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_0
    pid: {p: 5600.0, i: 22400.0, d: 924.0} #change these values to adjust kP, kI and kD of joint 0
  joint_1_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_1
    pid: {p: 4000.0, i: 9846.0, d: 1000.0} #change these values to adjust kP, kI and kD of joint 1
  joint_2_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_2
    pid: {p: 2500.0, i: 4819.2, d: 548.0} #change these values to adjust kP, kI and kD of joint 2