
DESE3R:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100
  
  # Position Controllers ---------------------------------------
  joint_0_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_0
    pid: {p: 140.0, i: 510.0, d: 50.0} #change these values to adjust kP, kI and kD of joint 0
  joint_1_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_1
    pid: {p: 80.0, i: 128.0, d: 80.0} #change these values to adjust kP, kI and kD of joint 1
  joint_2_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_2
    pid: {p: 50.0, i: 80.0, d: 20.6} #change these values to adjust kP, kI and kD of joint 2